Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-10-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-20-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-30-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-40-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-50-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-60-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-70-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-80-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-90-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-100-rand.config >>happy_buddha.k46.kdop.1.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-10-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-20-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-30-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-40-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-50-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-60-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-70-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-80-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-90-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-100-rand.config >>happy_buddha.k46.kdop.2.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-10-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-20-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-30-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-40-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-50-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-60-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-70-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-80-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-90-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-100-rand.config >>happy_buddha.k46.kdop.3.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-10-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-20-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-30-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-40-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-50-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-60-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-70-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-80-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-90-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-100-rand.config >>happy_buddha.k46.kdop.4.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-10-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-20-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-30-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-40-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-50-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-60-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-70-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-80-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-90-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/happy_buddha.obj -A do -r config/04-03-100-rand.config >>happy_buddha.k46.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k46.kdop.1.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k46.kdop.1.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k46.kdop.1.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k46.kdop.1.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k46.kdop.1.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k46.kdop.1.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k46.kdop.2.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k46.kdop.2.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k46.kdop.2.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k46.kdop.2.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k46.kdop.2.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k46.kdop.2.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k46.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k46.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k46.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k46.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k46.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k46.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k46.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k46.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k46.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k46.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k46.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k46.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k46.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k46.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k46.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k46.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k46.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k46.kdop.5.log
