Bench.exe -g file -f models/apple.obj -A do -r config/04-03-10-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-20-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-30-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-40-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-50-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-60-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-70-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-80-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-90-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-100-rand.config >>apple.k46.kdop.1.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-10-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-20-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-30-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-40-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-50-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-60-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-70-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-80-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-90-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-100-rand.config >>apple.k46.kdop.2.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-10-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-20-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-30-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-40-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-50-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-60-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-70-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-80-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-90-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-100-rand.config >>apple.k46.kdop.3.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-10-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-20-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-30-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-40-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-50-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-60-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-70-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-80-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-90-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-100-rand.config >>apple.k46.kdop.4.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-10-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-20-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-30-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-40-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-50-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-60-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-70-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-80-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-90-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/apple.obj -A do -r config/04-03-100-rand.config >>apple.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k46.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k46.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k46.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k46.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-10-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-20-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-30-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-40-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-50-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-60-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-70-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-80-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-90-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-100-rand.config >>dinosaur.k46.kdop.1.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-10-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-20-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-30-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-40-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-50-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-60-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-70-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-80-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-90-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-100-rand.config >>dinosaur.k46.kdop.2.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-10-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-20-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-30-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-40-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-50-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-60-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-70-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-80-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-90-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-100-rand.config >>dinosaur.k46.kdop.3.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-10-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-20-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-30-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-40-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-50-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-60-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-70-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-80-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-90-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-100-rand.config >>dinosaur.k46.kdop.4.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-10-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-20-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-30-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-40-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-50-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-60-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-70-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-80-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-90-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/dinosaur.obj -A do -r config/04-03-100-rand.config >>dinosaur.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-10-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-20-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-30-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-40-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-50-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-60-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-70-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-80-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-90-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-100-rand.config >>bunny2.k46.kdop.1.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-10-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-20-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-30-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-40-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-50-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-60-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-70-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-80-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-90-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-100-rand.config >>bunny2.k46.kdop.2.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-10-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-20-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-30-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-40-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-50-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-60-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-70-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-80-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-90-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-100-rand.config >>bunny2.k46.kdop.3.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-10-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-20-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-30-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-40-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-50-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-60-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-70-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-80-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-90-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-100-rand.config >>bunny2.k46.kdop.4.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-10-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-20-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-30-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-40-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-50-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-60-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-70-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-80-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-90-rand.config >>bunny2.k46.kdop.5.log
Bench.exe -g file -f models/bunny2.obj -A do -r config/04-03-100-rand.config >>bunny2.k46.kdop.5.log
