Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k24.kdop.1.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k24.kdop.2.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k24.kdop.3.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k24.kdop.4.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-10-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-20-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-30-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-40-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-50-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-60-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-70-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-80-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-90-rand.config >>budda.k24.kdop.5.log
Bench.exe -g file -f models/budda.obj -A do -r config/04-03-100-rand.config >>budda.k24.kdop.5.log
