Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k24.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k24.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k24.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k24.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k24.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k24.kdop.3.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k24.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k24.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k24.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k24.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k24.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k24.kdop.4.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-10-rand.config >>hand.k24.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-20-rand.config >>hand.k24.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-30-rand.config >>hand.k24.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-40-rand.config >>hand.k24.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-50-rand.config >>hand.k24.kdop.5.log
Bench.exe -g file -f models/hand.obj -A do -r config/04-03-60-rand.config >>hand.k24.kdop.5.log
